# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_addwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(498, 272)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lo_format = QtWidgets.QHBoxLayout()
        self.lo_format.setObjectName("lo_format")
        self.lb_format = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_format.sizePolicy().hasHeightForWidth())
        self.lb_format.setSizePolicy(sizePolicy)
        self.lb_format.setObjectName("lb_format")
        self.lo_format.addWidget(self.lb_format)
        self.cb_format = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_format.sizePolicy().hasHeightForWidth())
        self.cb_format.setSizePolicy(sizePolicy)
        self.cb_format.setObjectName("cb_format")
        self.cb_format.addItem("")
        self.cb_format.addItem("")
        self.lo_format.addWidget(self.cb_format)
        self.gridLayout.addLayout(self.lo_format, 1, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 1, 4, 1)
        self.lo_path = QtWidgets.QHBoxLayout()
        self.lo_path.setObjectName("lo_path")
        self.lb_path = QtWidgets.QLabel(Form)
        self.lb_path.setObjectName("lb_path")
        self.lo_path.addWidget(self.lb_path)
        self.le_path = QtWidgets.QLineEdit(Form)
        self.le_path.setObjectName("le_path")
        self.lo_path.addWidget(self.le_path)
        self.btn_pathfinder = QtWidgets.QToolButton(Form)
        self.btn_pathfinder.setObjectName("btn_pathfinder")
        self.lo_path.addWidget(self.btn_pathfinder)
        self.gridLayout.addLayout(self.lo_path, 2, 0, 1, 4)
        self.lo_link = QtWidgets.QHBoxLayout()
        self.lo_link.setObjectName("lo_link")
        self.lb_link = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_link.sizePolicy().hasHeightForWidth())
        self.lb_link.setSizePolicy(sizePolicy)
        self.lb_link.setObjectName("lb_link")
        self.lo_link.addWidget(self.lb_link)
        self.le_link = QtWidgets.QLineEdit(Form)
        self.le_link.setObjectName("le_link")
        self.lo_link.addWidget(self.le_link)
        self.gridLayout.addLayout(self.lo_link, 0, 0, 1, 4)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 4)
        self.btn_exit = QtWidgets.QDialogButtonBox(Form)
        self.btn_exit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout.addWidget(self.btn_exit, 8, 3, 1, 1)
        self.lo_checkbox = QtWidgets.QVBoxLayout()
        self.lo_checkbox.setObjectName("lo_checkbox")
        self.cb_custom_file_name = QtWidgets.QCheckBox(Form)
        self.cb_custom_file_name.setTristate(False)
        self.cb_custom_file_name.setObjectName("cb_custom_file_name")
        self.lo_checkbox.addWidget(self.cb_custom_file_name)
        self.cb_thumbnail = QtWidgets.QCheckBox(Form)
        self.cb_thumbnail.setObjectName("cb_thumbnail")
        self.lo_checkbox.addWidget(self.cb_thumbnail)
        self.cb_subtitle = QtWidgets.QCheckBox(Form)
        self.cb_subtitle.setObjectName("cb_subtitle")
        self.lo_checkbox.addWidget(self.cb_subtitle)
        self.gridLayout.addLayout(self.lo_checkbox, 5, 0, 4, 1)
        self.lb_option = QtWidgets.QLabel(Form)
        self.lb_option.setObjectName("lb_option")
        self.gridLayout.addWidget(self.lb_option, 3, 0, 1, 1)
        self.lo_filename = QtWidgets.QHBoxLayout()
        self.lo_filename.setObjectName("lo_filename")
        self.lb_filename = QtWidgets.QLabel(Form)
        self.lb_filename.setObjectName("lb_filename")
        self.lo_filename.addWidget(self.lb_filename)
        self.le_filename = QtWidgets.QLineEdit(Form)
        self.le_filename.setEnabled(False)
        self.le_filename.setObjectName("le_filename")
        self.lo_filename.addWidget(self.le_filename)
        self.gridLayout.addLayout(self.lo_filename, 6, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_format.setText(_translate("Form", "Select format : "))
        self.cb_format.setItemText(0, _translate("Form", "mp4"))
        self.cb_format.setItemText(1, _translate("Form", "mp3"))
        self.lb_path.setText(_translate("Form", "output path : "))
        self.btn_pathfinder.setText(_translate("Form", "..."))
        self.lb_link.setText(_translate("Form", "Youtube Link : "))
        self.cb_custom_file_name.setText(_translate("Form", "custom file name"))
        self.cb_thumbnail.setText(_translate("Form", "with thumbnail"))
        self.cb_subtitle.setText(_translate("Form", "with subtitle"))
        self.lb_option.setText(_translate("Form", "Option"))
        self.lb_filename.setText(_translate("Form", "filename:"))
