# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 549)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_monitor = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_monitor.sizePolicy().hasHeightForWidth())
        self.tw_monitor.setSizePolicy(sizePolicy)
        self.tw_monitor.setMinimumSize(QtCore.QSize(0, 0))
        self.tw_monitor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tw_monitor.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tw_monitor.setAutoFillBackground(False)
        self.tw_monitor.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw_monitor.setDragEnabled(False)
        self.tw_monitor.setDragDropOverwriteMode(True)
        self.tw_monitor.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tw_monitor.setAlternatingRowColors(True)
        self.tw_monitor.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tw_monitor.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_monitor.setObjectName("tw_monitor")
        self.tw_monitor.setColumnCount(7)
        self.tw_monitor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tw_monitor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_monitor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_monitor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_monitor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_monitor.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_monitor.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_monitor.setHorizontalHeaderItem(6, item)
        self.tw_monitor.horizontalHeader().setVisible(True)
        self.tw_monitor.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_monitor.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tw_monitor, 0, 0, 1, 1)
        self.lo_control = QtWidgets.QHBoxLayout()
        self.lo_control.setObjectName("lo_control")
        self.btn_addLink = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addLink.setObjectName("btn_addLink")
        self.lo_control.addWidget(self.btn_addLink)
        self.btn_editLink = QtWidgets.QPushButton(self.centralwidget)
        self.btn_editLink.setObjectName("btn_editLink")
        self.lo_control.addWidget(self.btn_editLink)
        self.btn_deleteLink = QtWidgets.QPushButton(self.centralwidget)
        self.btn_deleteLink.setObjectName("btn_deleteLink")
        self.lo_control.addWidget(self.btn_deleteLink)
        self.gridLayout.addLayout(self.lo_control, 1, 0, 1, 1)
        self.lo_start = QtWidgets.QHBoxLayout()
        self.lo_start.setObjectName("lo_start")
        self.progressbar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressbar.setProperty("value", 24)
        self.progressbar.setObjectName("progressbar")
        self.lo_start.addWidget(self.progressbar)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setObjectName("btn_start")
        self.lo_start.addWidget(self.btn_start)
        self.gridLayout.addLayout(self.lo_start, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tw_monitor.setSortingEnabled(True)
        item = self.tw_monitor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Link"))
        item = self.tw_monitor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "format"))
        item = self.tw_monitor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "output path"))
        item = self.tw_monitor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "custom name"))
        item = self.tw_monitor.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "thumbnail"))
        item = self.tw_monitor.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "subtitle"))
        item = self.tw_monitor.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "done"))
        self.btn_addLink.setText(_translate("MainWindow", "Add"))
        self.btn_editLink.setText(_translate("MainWindow", "Edit"))
        self.btn_deleteLink.setText(_translate("MainWindow", "Delete"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
